export const LOAD_JOB_APPS = 'LOAD_JOB_APPS';

export const ADD_JOB_APP = 'ADD_JOB_APP';

export const UPDATE_NEW_COMPANY = 'UPDATE_NEW_COMPANY';

export const UPDATE_NEW_POSITION = 'UPDATE_NEW_POSITION';

export const UPDATE_NEW_DATE = 'UPDATE_NEW_DATE';

export const UPDATE_NEW_STATUS = 'UPDATE_NEW_STATUS';
